# Generated by Django 4.2.11 on 2024-04-10 08:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0002_quizquestions"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="quizcategory",
            options={"verbose_name_plural": "Quiz Categories"},
        ),
        migrations.AlterModelOptions(
            name="quizquestions",
            options={"verbose_name_plural": "Quiz Questions"},
        ),
    ]
