# Generated by Django 4.2.11 on 2024-04-12 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0005_usercategoryattempts"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usercategoryattempts",
            name="question",
        ),
        migrations.AddField(
            model_name="usercategoryattempts",
            name="category",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="quiz.quizcategory",
            ),
        ),
        migrations.AlterField(
            model_name="quizquestions",
            name="level",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="quizquestions",
            name="time_limit",
            field=models.IntegerField(null=True),
        ),
    ]
